### ISSUE TITLE
Mac OS X - build error

### ISSUE THREAD

**Issue by tmarrinan** [ornladios/ADIOS#111]
Hello.
I am getting an error attempting to build ADIOS on Mac OS X. I have CMake, MPI, and Python installed. After cloning the repo, I can use CMake to generate a Makefile, but when I type 'make', I get the following error:

```
In file included from <path>/ADIOS/src/core/adios_clock.c:12:
<path>/ADIOS/src/core/adios_clock.h:16:17: error: typedef redefinition with
      different types ('int' vs 'enum clockid_t')
    typedef int clockid_t;
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: 
      previous definition is here
} clockid_t;
  ^
1 error generated.
```

**Comment by pnorbert** [comment]
Hi,
What compiler did you set to CC before running cmake?
I have CC=mpicc and it will use the /usr/include/time.h, which does not
have this type defined in it. Your compiler is accessing the header in
Xcode.
Nevertheless this is a bug since the cmake configuration does not check for
the existence of this type as the autoconf build does.

**Comment by tmarrinan** [comment]
I changed CMAKE_CXX_COMPILER to /usr/local/bin/mpic++ and  CMAKE_C_COMPILER to /usr/local/bin/mpicc in the CMake GUI before generating the Makefile. Is there anything else needed to set CC to mpicc or CXX to mpic++?

**Comment by pnorbert** [comment]
I pushed a fix. Please try it again.

**Comment by tmarrinan** [comment]
I am still getting the same error.
If it matters, there is no file /usr/include/time.h on my machine. I am using MPICH version 3.2, installed via homebrew.

**Comment by pnorbert** [comment]
What is the value in config.h after running cmake for

/* Define to 1 if the system has the type `clockid_t'. */
#define HAVE_CLOCKID_T 1

**Comment by tmarrinan** [comment]
It is commented out:
/* Define to 1 if the system has the type `clockid_t'. */
/* #undef HAVE_CLOCKID_T */

**Comment by pnorbert** [comment]
So cmake does not find this type when looking for it, but the compiler will
complain when we define it in ADIOS. I cannot replicate your problem and
don't know what is wrong with my fix that works both on my Mac (I have
/usr/include/time.h without this type) and Linux (which has this type).
Can you build ADIOS with its autoconf build?

**Comment by tmarrinan** [comment]
Looking at the User Manual, I should be able to do:
`../configure -prefix=<install-dir>`

However, there is no configure file, so that command fails.

If I try to execute runconf, I get the following:
```
Could not determine what machine is this.
This script is for configuring adios on the authors' machines.
You can study it to figure out how to configure adios on your system.
```

Looking at the script, I'm not sure how to edit it.

**Comment by pnorbert** [comment]
./autogen.sh first, then configure.
runconf is a collection of setups for many machines. you can add a section
for your own machine if you don't want to manually configure it.

**Comment by tmarrinan** [comment]
When running ./autogen.sh, I get the following:
```
./autogen.sh: line 2: aclocal: command not found
./autogen.sh: line 3: libtoolize: command not found
./autogen.sh: line 4: autoconf: command not found
./autogen.sh: line 5: autoheader: command not found
./autogen.sh: line 6: automake: command not found
```

**Comment by pnorbert** [comment]
homebrew install automake autoconf

**Comment by tmarrinan** [comment]
libtoolize does not work on Mac OS X - it is glibtoolize instead (libtool conflicts with native utility).
I modified the autogen.sh, then it ran successfully (configure, build, and install).

**Comment by pnorbert** [comment]
sorry I forgot about that piece of detail

**Comment by tmarrinan** [comment]
No problem - thanks for the help with the install!

**Comment by pnorbert** [comment]
Welcome. I did not find a mac around here that has no /usr/include/time.h
so I don't know how to proceed testing the cmake build.
