### ISSUE TITLE
Numpy: OOP Wrapper & h5py

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#56]
@yyalli I am splitting this thread from issue #53 since I accidentally went OT there.

--

It would also be great if we could bring the general interface closer to [`h5py`](http://docs.h5py.org/en/latest/quick.html) since this would make many scripts easily portable, accessing a huge community of people already using h5py and one can benefit from a very easy interface (that ADIOS can extend where necessary, e.g., for transport methods).

Some points:
- `.file` -> `.File` (upper case in the read API)
- `.attr` -> `.attrs` renaming
- emulating that each group and each variable object can in turn again have a `.attrs` member (that simply checks the global list of attributes for attributes that share the same prefix)

Here is an example that allows to create **objects** for individual (sub-)groups and variables, making programming way easier for users:

```python
import adios as ad

f = ad.file("adios_test.bp")
t = f["temperature"] # type: adios.var

# here t could have a member dictionary attr(s) again
# which looks up all attributes starting with t.name
# now match: f.attrs["/temperature/description"]
print( t.attrs["description"] )

# the same should be possible for groups
g = f["someSubGroup/anOtherGroup/"] # type: adios.group
# now match: f.attrs["/someSubGroup/anOtherGroup/anOtherAttribute"]
print( g.attrs["anOtherAttribute"] )
# now match: f["/someSubGroup/anOtherGroup/anOtherVariable"]
print( g["anOtherVariable"] )
```

I know that attributes are currently stored as a list and the full path is the identifier in `bp`, nevertheless the numpy API can just abstract and "visualize" these objects by simple string-matching.

I am writing this because I am urgently in the need to have our [openPMD validator scripts](https://github.com/openPMD/openPMD-validator) for ADIOS, too. But to keep them maintainable it would be extremely helpful to have the ADIOS numpy wrapper in a clean OOP style [such as the one from h5py](http://docs.h5py.org/en/latest/quick.html) (also [on github](https://github.com/h5py/h5py)).

We are also using the numpy wrapper in our project [pyDive](https://github.com/ComputationalRadiationPhysics/pyDive) that is already struggling with missing OOP in the wrapper. We would really like to include the wrapper in [openPMD-viewer](https://github.com/openPMD/openPMD-viewer) with the LBNL and DESY folks but also here, more OOP as in the example above would help a lot.

When working with the python community we need to be aware that Python is not C, so interfaces need to be in object-centric, with object methods rather than function calls and well-documented via *DocStrings* ([PEP8](https://www.python.org/dev/peps/pep-0008/) [PEP257](https://www.python.org/dev/peps/pep-0257)). Python users work interactively via [ipython](https://ipython.org/) and query DocStrings, e.g., with `object?` and `object.method?`. Python developers like abstracting things into modules, so changing an `import h5py as io` to `import adios as io` should be all that is necessary for a first serial reader and writer to become "ADIOS". Also, [documentation can be auto-generated](http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/) via Sphinx/ReadTheDocs and we could add examples/tests and if you like [travis-ci tests during development](https://docs.travis-ci.com/user/languages/python). It might also be a good idea to split the wrappers from the main repo and include adios as a `git submodule` to keep the changing APIs and updates controllable.

Last but not least, [HDF Compass](https://github.com/HDFGroup/hdf-compass) could get a very simple backend implementation with ADIOS as soon as the wrapper is a bit more object oriented. This would automatically "equip" ADIOS with a GUI such as users know it from [HDFView](https://www.hdfgroup.org/products/java/hdfview/).

**Comment by ax3l** [comment]
Moved from https://github.com/ornladios/ADIOS/issues/53#issuecomment-164554174:

```
Hi, Axel,

Sorry for my late reply.

I partially implemented attaching attrs to variables. Recent examples can be found
in wrapper/numpy/tests/test_adios_attribute.py

However, I haven't implemented the group concept yet. Please try the example and
let me know if this update works for you or not.
```

**Comment by ax3l** [comment]
@yyalli I am sorry for the late answer: yes, the `.attrs` attribute on `adios.var` objects works great for me in your example.

Unfurtunately it does not work with the example I provided above for the file `wrappers/numpy/tests/adios_test.bp`:
```python
import adios as ad

f = ad.file("adios_test.bp")
t = f["temperature"]

f.var.keys()
# ['NX',
# '/__adios__/timer_labels_1',
# '/__adios__/timers_1',
# 'temperature',
# 'size']
f.attrs.keys()
# ['/temperature/description']

f.attrs.keys()
# ['/temperature/description']
t.attrs.keys()
# [] # should not be empty
```

**Comment by yyalli** [comment]
Leading '/' caused the error. Now added a routine to handle with and without the leading '/' character.

**Comment by ax3l** [comment]
yes exactly. Fantastic solution, thank you! :sparkles:

**Comment by ax3l** [comment]
Oh wait, the groups are still missing. Sorry for the clumsy issue.

**Comment by yyalli** [comment]
Sorry for the late update. I have added "group" feature. Can you check again?

**Comment by ax3l** [comment]
oh wonderful!
I tested the reader with a not-to complex example and it looks great!

The `adios.writer` seems to segfault on `fileObject.declare_group("myGroup")` right now.

Currently, newly created groups are not detected in the `writer`:
```python
import adios as ad

f = ad.Writer("example.bp")
f.attrs["/group/testAttr"] = 3
g = f["/group"] # or "group" or "/group/"
# KeyError: '/group'
```

and `fileObj.close()` seems not to work:
```python
import adios as ad

f = ad.Writer("example.bp")
f.close()
# adios.pyx in adios.writer.close (adios.cpp:21719)()
# TypeError: expected string or Unicode object, NoneType found
```

**Comment by ax3l** [comment]
There seem to be some problems with reading nested groups. Example:
```bash
$ bpls -a example.bp
  real                /data/0/fields/FieldE/x                       {10240, 8320}
  real                /data/0/fields/FieldE/y                       {10240, 8320}
[...]
  unsigned long long  /data/0/particles/e/particles_info            {40}
  unsigned long long  /data/0/particles/i/particles_info            {40}
  real                /data/0/particles/e/position/x                {5646994}
  real                /data/0/particles/e/position/y                {5646994}
  real                /data/0/particles/e/momentum/x                {5646994}
[...]
  integer             /data/0/particles/i/globalCellIdx/x           {5646994}
  integer             /data/0/particles/i/globalCellIdx/y           {5646994}
  double              /data/0/fields/FieldE/x/sim_unit              attr
  double              /data/0/fields/FieldE/y/sim_unit              attr
[...]
  unsigned integer    /data/0/iteration                             attr
  unsigned integer    /data/0/sim_slides                            attr
  real                /data/0/delta_t                               attr
  real                /data/0/cell_width                            attr
  real                /data/0/cell_height                           attr
[...]
```

```python
import adios as ad

f = ad.file("example.bp")

# OK:
g = f["data/0"]

# all these fail:
g = f["data"]
g = f["/data"]
g = f["/data/"]
g = f["data/0/"]
g = f["/data/0"]
```

**Comment by yyalli** [comment]
I have fixed for the nested groups. Can you try again?

**Comment by yyalli** [comment]
I have also fixed the segfault error with declare_group and the NoneType error on closing.

**Comment by ax3l** [comment]
> I have also fixed the segfault error with declare_group and the NoneType error on closing.

`declare_group` and `close() work now, thank you!

> I have fixed for the nested groups. Can you try again?

The following example does still not work:

```python
import adios as ad

f = ad.Writer("example.bp")

f.declare_group("group1")
g1 = f["group1"]
# KeyError: 'group1'

# create group implicitly
f.attrs["/group2/testAttr"] = 3
g2 = f["/group2"] # or "group2" or "/group2/"
# KeyError: '/group2'

# OK
a = f.attrs["/group2/testAttr"]
# fails
b = f.attrs["group2/testAttr"]
# KeyError: 'group2/testAttr'
```
